name: Render and deploy quarto files

on:
  push:
    branches: website
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Update apt-get
        run: sudo apt-get update

      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - run: pip install -r requirements.txt

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # Pin to the Quarto version you use locally (check with `quarto --version`)
          version: 1.8.24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add TinyTeX to PATH
        run: echo "$HOME/.TinyTeX/bin/x86_64-linux" >> "$GITHUB_PATH"

      - name: Install required LaTeX packages
        run: |
          tlmgr update --self
          tlmgr install moderncv fontawesome6

      - name: Render and Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions